print("Welcome to the tip calculator!")
rechnung=input("What was the total bill?")
print(rechnung)
trinkgeldsatz=input("How much tip would you like tog give? 10,12, or 15? ")
print(trinkgeldsatz)
anzahlpersonen=input("How many people to split the bill?")
print(anzahlpersonen)
trinkgeld=(int(rechnung)*(int(trinkgeldsatz)/100)/int(anzahlpersonen))
trinkgeld=round(trinkgeld,2)
print(f"Each person should pay {trinkgeld}")